services:
  app:
    container_name: ext_playground
    build:
      context: .
      dockerfile: prod.Dockerfile
    working_dir: /extension
    command: swoext run --no-color
    volumes:
      - .:/extension
    env_file:
      - .env
    ports:
      - "8080:8080"
    expose:
      - "8080"

  bash:
    container_name: ext_playground_bash
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .env

  app_test:
    container_name: ext_playground_test
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "ruff format --check . && ruff check . && flake8 . && mypy . && uv lock --check && pytest"
    volumes:
      - .:/extension
    environment:
      - PROCESS_CHECK_INTERVAL_SECS=0
    env_file:
      - .env

  format:
    container_name: ext_playground_format
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /extension
    command: bash -c "ruff check --select I --fix . && ruff format ."
    volumes:
      - .:/extension
    env_file:
      - .env
